In [162]:
import numpy as np
from scipy.linalg import lu

a = np.array([[2.,4.,4.,4.],[1.,2.,3.,3.],[1.,2.,2.,2.],[1.,4.,3.,4.]])
p, l, u = lu(a)

In [163]:
p

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  1.,  0.,  0.]])

In [140]:
b = np.dot(p , u)
print(a)
print("---分隔線---")
print(b)

[[ 2.  4.  4.  4.]
 [ 1.  2.  3.  3.]
 [ 1.  2.  2.  2.]
 [ 1.  4.  3.  4.]]
---分隔線---
[[ 2.  4.  4.  4.]
 [ 0.  0.  1.  1.]
 [ 0.  0.  0.  0.]
 [ 0.  2.  1.  2.]]


In [126]:
print(a[0], "Linear Independent")
print(a[1], "Linear Independent")
print(a[2], "Linear Dependent")
print(a[3], "Linear Independent")

[ 2.  4.  4.  4.] Linear Independent
[ 1.  2.  3.  3.] Linear Independent
[ 1.  2.  2.  2.] Linear Dependent
[ 1.  4.  3.  4.] Linear Independent


In [385]:
def swap_rows(arr, frm, to):#換array中列的公式
    arr[[frm, to],:] = arr[[to, frm],:]

In [386]:
C = np.array([[1.0,1.5,-2.0],[2.0,1.0,-1],[3.0,-1.0,2.0],[2,3,-4],[1,1,1]])
C

array([[ 1. ,  1.5, -2. ],
       [ 2. ,  1. , -1. ],
       [ 3. , -1. ,  2. ],
       [ 2. ,  3. , -4. ],
       [ 1. ,  1. ,  1. ]])

In [387]:
def finddeadwood(M): # 找冗員公式
    p, l, u = lu(M)
    h = np.dot(p,l)
    a = np.dot(h,u)#矩陣原來的長相
    m = len(M)#矩陣有幾列
    n = len(M[0])#矩陣有幾行
    for r in range(0,min(n,m)): #做到第幾次   
        if(M[r][r]==0): # 發現如果是零的處理方法，就跟下面絕對值最大的那一列換
            k = np.argmax(np.absolute(M[r+1:m]),axis=0)[r]#去掉前面後的最大絕對值那一行
            g = r+1+k#全部裡面那一行最大的位置
            swap_rows(M,r,g)
            print(a[g], "Linear Independent")
        for j in range(r,m-1):#每一列
            c = M[j+1][r]/M[r][r]
            for i in range(r,n):#每一列中的每一項
                M[j+1][i] = M[j+1][i] - c*M[r][i]    
        print(a[r], "Linear Independent")
        print(M)
    print(a)

In [388]:
finddeadwood(C)

[ 1.   1.5 -2. ] Linear Independent
[[ 1.   1.5 -2. ]
 [ 0.  -2.   3. ]
 [ 0.  -5.5  8. ]
 [ 0.   0.   0. ]
 [ 0.  -0.5  3. ]]
[ 2.  1. -1.] Linear Independent
[[ 1.    1.5  -2.  ]
 [ 0.   -2.    3.  ]
 [ 0.    0.   -0.25]
 [ 0.    0.    0.  ]
 [ 0.    0.    2.25]]
[ 3. -1.  2.] Linear Independent
[[ 1.    1.5  -2.  ]
 [ 0.   -2.    3.  ]
 [ 0.    0.   -0.25]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]]
[[ 1.   1.5 -2. ]
 [ 2.   1.  -1. ]
 [ 3.  -1.   2. ]
 [ 2.   3.  -4. ]
 [ 1.   1.   1. ]]
