In [1]:
import numpy as np

In [ ]:
#example source:https://www.baseball-reference.com/players/b/bettsmo01.shtml

In [ ]:
#以美國職棒大聯盟選手Mookie Betts為例，以下是他今年以及去年的個人成績，分別是（出賽場數/打席/打數/得分/安打/全壘打/打點/盜壘）等成績，
#我們想要知道兩年總成績，只要分別將兩年成績設為矩陣相加

In [2]:
record2017 = np.array([[153,712,628,101,166,24,102,26]])

In [6]:
record2016 = np.array([[158,730,672,122,214,31,113,26]])

In [8]:
recordtwoyears = record2016 + record2017
recordtwoyears

array([[ 311, 1442, 1300,  223,  380,   55,  215,   52]])

In [ ]:
#接著我們想要知道他總共得的壘打數，算法是（安打*1＋二壘打*2＋三壘打*3＋全壘打*4）
#於是將今年成績設定成一個矩陣，再將倍數設成另一個，將兩者相乘

In [48]:
singles2017 = np.array([[166,46,2,24]])
singles2017

array([[166,  46,   2,  24]])

In [53]:
bases = np.array([1,2,3,4])
bases

array([1, 2, 3, 4])

In [55]:
totalbases2017 = singles2017.dot(bases)
totalbases2017

array([360])

In [ ]:
#最後我們想計算今年美國聯盟東區個隊伍的季賽勝率，分別是（紅襪/洋基/藍鳥/光芒/金鶯）
#將他們今年的勝場設成一個矩陣，因為一年總共162場比賽，於是乘上(1/162)即可知道勝率

In [ ]:
#Winning percentage source:http://mlb.mlb.com/mlb/standings/index.jsp#20171001

In [56]:
ALEast = np.array([[93],[91],[80],[76],[75]])

In [58]:
winspercentages = ALEast * (1/162)
winspercentages

array([[ 0.57407407],
       [ 0.5617284 ],
       [ 0.49382716],
       [ 0.4691358 ],
       [ 0.46296296]])