In [41]:
import numpy as np

In [44]:
I = int(input("How many raws do you want?(postive number)"))
J = int(input("How many columns do you want?(postive number)"))
K = int(input("Which range do you want?(postive number)"))
L = np.random.randint(1,K,int(I*J)).reshape((I,J))
L

How many raws do you want?(postive number)5
How many columns do you want?(postive number)4
Which range do you want?(postive number)100


array([[83, 24, 32, 74],
       [75, 28, 15, 92],
       [15, 32, 72, 65],
       [79, 81, 60, 77],
       [33, 11, 59, 82]])

In [45]:
transposeL = np.transpose(L)
transposeL

array([[83, 75, 15, 79, 33],
       [24, 28, 32, 81, 11],
       [32, 15, 72, 60, 59],
       [74, 92, 65, 77, 82]])

In [46]:
M = int(input("What size of square matrix do you want?(postive number)"))
N = int(input("Which range do you want?(postive number)"))
O = np.random.randint(1,N,M**2).reshape((M,M))
O

What size of square matrix do you want?(postive number)9
Which range do you want?(postive number)10


array([[8, 9, 1, 1, 7, 7, 2, 4, 5],
       [9, 5, 9, 2, 3, 9, 1, 8, 4],
       [6, 9, 8, 9, 4, 7, 6, 5, 6],
       [1, 4, 3, 1, 3, 4, 4, 3, 3],
       [8, 2, 8, 7, 3, 9, 9, 6, 2],
       [8, 8, 1, 1, 5, 1, 8, 2, 3],
       [4, 1, 4, 3, 6, 4, 3, 1, 7],
       [5, 6, 7, 1, 4, 7, 2, 6, 4],
       [4, 5, 7, 2, 9, 4, 9, 9, 7]])

In [47]:
traceO = np.trace(O)
traceO

42